jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust to your Java version
          distribution: 'adopt'
          
      # Create an application-test.properties file for tests
      - name: Setup test database configuration
        run: |
          mkdir -p backend/src/test/resources
          echo "spring.datasource.url=jdbc:mysql://localhost:3306/testdb" > backend/src/test/resources/application-test.properties
          echo "spring.datasource.username=root" >> backend/src/test/resources/application-test.properties
          echo "spring.datasource.password=root" >> backend/src/test/resources/application-test.properties
          echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> backend/src/test/resources/application-test.properties
          echo "spring.jpa.hibernate.ddl-auto=create-drop" >> backend/src/test/resources/application-test.properties
      
      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml
