name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Required for the dependency graph submission
    permissions:
      contents: write
      security-events: write
      id-token: write

    services:
      # MySQL service container for testing
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: GreenGrub
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file backend/pom.xml
    
    - name: Run tests
      run: mvn -f backend/pom.xml test
      
    # Using @v4.0.0 specifically to avoid issues with later versions
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4.0.0
      with:
        directory: './backend'
        # Optional: provide a specific token if the default doesn't work
        token: ${{ github.token }}
